add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
repo_root_style = "bold cyan"
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
ahead = "⇡${count} "
behind = "⇣${count} "
conflicted = " "
deleted = ""
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
format = "[$all_status]($style)"
modified = " "
renamed = ""
staged = ""
stashed = ""
style = "cyan"
untracked = "? "
up_to_date = " "
